[package]
name = "circom2soroban"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
num-bigint = "0.4"
ark-serialize = { version = "0.4.2" }
soroban-sdk = { workspace = true, features = ["testutils"] }