[package]
name = "poseidon"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
ark-bls12-381 = "0.4"
ark-ff = "0.4"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
