[package]
name = "lean-imt"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
poseidon = { path = "../poseidon" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
